import type { SectionKey } from "./Sections";

export const ALIASES: Record<string, SectionKey> = {
  help: "help",
  "?": "help",
  man: "help",
  whoami: "about",
  about: "about",
  bio: "about",
  id: "about",
  experience: "work",
  work: "work",
  history: "work",
  jobs: "work",
  career: "work",
  projects: "projects",
  project: "projects",
  selected: "projects",
  ls: "projects",
  tools: "tools",
  stack: "tools",
  toolbox: "tools",
  skills: "tools",
  tech: "tools",
  resume: "resume",
  cv: "resume",
  résumé: "resume",
  contact: "contact",
  connect: "contact",
  hi: "contact",
  say: "contact",
  mail: "contact",
  email: "contact",
  surprise: "game",
  play: "game",
  snake: "game",
  game: "game",
  secret: "game",
  easter: "game",
  boo: "game",
  psst: "game",
  arcade: "game",
};
